<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;
use app\models\UploadFile;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "car".
 *
 * @property integer $id
 * @property integer $company_id
 * @property string $name
 * @property string $code
 * @property string $type
 * @property integer $year
 * @property integer $speed
 * @property string $engine
 * @property string $color
 * @property string $transmission
 * @property string $privod
 * @property string $description
 * @property integer $price
 * @property integer $discount_1
 * @property integer $discount_2
 * @property string $img
 * @property integer $up_date
 *
 * @property Company $company
 * @property UploadFile $file
 * @property Order[] $orders
 */
class Car extends \yii\db\ActiveRecord
{
    const SCENARIO_UPDATE = 'update';

    public $file;

    /**
     * Update up_date column when save and update model
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    self::EVENT_BEFORE_INSERT => ['up_date'],
                    self::EVENT_BEFORE_UPDATE => ['up_date']
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'car';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['company_id', 'year', 'speed', 'price', 'discount_1', 'discount_2'], 'integer'],
            [['name', 'code', 'type', 'year', 'speed', 'engine', 'color', 'transmission', 'privod', 'price', 'file'], 'required', 'on' => self::SCENARIO_DEFAULT],
            [['name', 'code', 'type', 'year', 'speed', 'engine', 'color', 'transmission', 'privod', 'price'], 'required', 'on' => self::SCENARIO_UPDATE],
            [['name', 'code'], 'string', 'max' => 50],
            [['type', 'engine', 'color', 'transmission', 'privod', 'description'], 'string', 'max' => 25],
            [['file'], 'file', 'extensions' => ['jpg', 'png', 'gif'], 'maxSize' => 1024 * 1024 * 5],
            [['code'], 'unique'],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => Company::className(), 'targetAttribute' => ['company_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'company_id' => 'ID марки',
            'name' => 'Название',
            'code' => 'Символьный код',
            'type' => 'Тип',
            'year' => 'Год производства',
            'speed' => 'Скорость',
            'engine' => 'Двигатель',
            'color' => 'Цвет',
            'transmission' => 'Transmission',
            'privod' => 'Привод',
            'description' => 'Описание',
            'price' => 'Цена',
            'discount_1' => 'Скидка 1 (3-7 дней)',
            'discount_2' => 'Скидка 2 (от 7 дней)',
            'file' => 'Картинка',
            'companyName' => 'Марка',
            'up_date' => 'Изменение'
        ];
    }

    /**
     *
     */
    public function save($runValidation = true, $attributeNames = null)
    {
        if ($file = UploadedFile::getInstance($this, 'file')){
            $this->file = new UploadFile($file);

            if (!$this->img = $this->file->save())
                $this->addError('file', 'Картинка не загружена');
        }

        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrders()
    {
        return $this->hasMany(Order::className(), ['car_id' => 'id']);
    }

    /**
     * @return string
     */
    public function getFullName()
    {
        return $this->company->name . ' ' . $this->name;
    }

    public function getCompanyName()
    {
        return $this->company->name;
    }
}
